artApp/artApp/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static
from django.conf import settings

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include("core.urls")),
    path('', include('django.contrib.auth.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

artApp/core/urls.py
from django.urls import re_path, path
from . import views
from django.contrib.auth import views as auth_views
from .forms import UserPasswordResetForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name="index"),
    path('categories', views.categories, name="categories"),
    path('login',views.user_login, name="login"),
    path('signup/',views.user_signup, name="signup"),
    path('logout/', views.user_logout, name='logout'),
    path('cart', views.shop_cart, name='cart'),
    path('artist', views.artist, name='artist'),
    path('update_item',views.update_item, name='updateItem'),
    path('delete_item',views.delete_item, name='deleteItem'),
    path('payment',views.payment, name='payment'),
    path('shipping',views.shipping, name='shipping'),
    path('edit',views.edit, name='edit'),
    path('about',views.about, name='about'),
    path('thanks',views.thanks, name='thanks'),
    path('404',views.not_found, name='notFound'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='users/password_reset.html',
         form_class=UserPasswordResetForm),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete')
]

artApp/artApp/templates/artist.html
{% extends 'layout.html' %}
{% load static %}
  {% block content %}
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12 py-4 p-xl-5">

          <h2 class="mb-4">{{item.title}} by {{ item.artist }}</h2>
          <a class="btn btn-outline-secondary" href="{% url 'core:index' %}">Back</a>

          <hr class="my-4">
          <div class="row">


                  <div class="row">
                    <div class="col-lg-8 col-md-12 col-sm-12">
                      <!-- Gallery grid with gutters -->
                      <div class="row pt-3 mx-n2 gallery">

                        <!-- Item -->
                        <div class="col-lg-6 col-md-6 col-sm-6 col-6 mb-grid-gutter">
                            <img style="border-radius: 5px;" class="card-img-top" src="{{ item.itemPhotoComplete.url }}">
                        </div>

                        <!-- Item -->
                        <div class="col-lg-6 col-md-6 col-sm-6 col-6 mb-grid-gutter">
                          <div >
                            <img style="border-radius: 5px;" class="card-img-top" src="{{ item.itemPhotoZoomIn.url }}">
                          </div>
                        </div>

                        <!-- Item -->
                        <div class="col-lg-6 col-md-6 col-sm-6 mb-grid-gutter">
                          <div >
                            <!-- <img style="border-radius: 5px;" class="card-img-top" src="{{ item.Video.url }}"  type="video/mp4"> -->
                            <!-- <video controls autoplay> <source src="movie.mp4" type="video/mp4"> <source src="movie.ogg" type="video/ogg"> Your browser does not support the video tag. </video> -->
                          </div>
                        </div>
                      </div>
                  </div>
                  <div class="col-lg-4 col-md-0 col-sm-0 col-0">
                    <div >
                      <!-- Item -->
                      <h6>{{item.title}}</h6>
                      <p class="card-text">{{item.artType}}<br>${{ item.price }}<br><span class="text-primary">{{ item.hours }} hours worked</span></p>
                      <p class="card-text fs-sm">{{item.description}}</p>
                      <!-- Pill outline button -->
                      <a href="/cart?item={{ item.id }}" class="btn btn-outline-primary rounded-pill">Add To My Cart</a>
                    </div>
                  </div>
                </div>

                {% if items %}
                <h5 class="mb-4 pt-3">More masterpieces by {{ artist.artistName }}</h5>
                <hr>

                <!-- Products grid-->
                <div class="row pt-3 mx-n2">
                  {% for item in items %}
                  <!-- Product-->
                  <div class="col-lg-3 col-md-4 col-sm-6 col-6 px-2 mb-4" data-marker-id="{{ item.id }}">
                    <div class="card " >
                      <a class="card-img-top d-block overflow-hidden" href="/artist?artist_id={{ item.artist.id }}&&item_id={{ item.id }}"><img src="{{ item.itemPhotoComplete.url }}" alt="Product"></a>
                      <div class="card-body py-2"><a class="product-meta d-block fs-xs pb-1" href="/artist?artist_id={{ item.artist.id }}&&item_id={{ item.id }}">by {{ item.artist }}</a>
                        <h3 class="product-title fs-sm"><a href="shop-single-v1.html">{{ item.title }}</a></h3>

                        <div class="d-flex justify-content-between">
                          <div class="product-price"><span class="text-primary">{{ item.hours }} hours spent on this masterpiece</span> <br>${{ item.price }}</div>
                          </div>
                        </div>
                      </div>
                    </div>
                  {% endfor %}
                </div>
                {% endif %}

                <!-- Artist grid-->
                <div class="row pt-3 mx-n2">
                <!-- Artist Photo-->
                <div class="col-lg-3 col-md-4 col-sm-3 col-3 px-2 mb-4" data-marker-id="{{ item.id }}">
                  <div class="card" >
                    <a class="card-img-top d-block overflow-hidden" style="border-radius: 5px;"><img src="{{ artist.artistPhoto.url }}"></a>
                  </div>
                  </div>

                  <!-- Artist Text-->
                  <div class="col-lg-9 col-md-8 col-sm-9 col-9 px-2 mb-4" data-marker-id="{{ item.id }}">
                    <div class="card " >
                      <div class="card-body py-2">
                        <h4 class="product-title py-3">{{ artist.artistName }}</h4>
                        <div class="d-flex justify-content-between">
                          <div class="product-price">{{ artist.artistText }}</div>
                          </div>
                        </div>
                      </div>
                    </div>

                    <hr class="d-sm-none">
                </div>






          </div>
        </div>




      </div>
    </div>


  {% endblock %}




  {% block js %}


  <!-- Async script executes immediately and must be after any DOM elements used in callback. -->
  <script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCAYmWw7M9sB8M6MAN-90VFsWafxdl4yMQ&callback=initMap&libraries=&v=weekly"
    async>
  </script>


  <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>

  <script type="text/javascript">

  function initMap() {
    // Create the map.
    const map = new google.maps.Map(document.getElementById("map"), {
       zoom: 9,
      center: { lat: {{ artist.lat }}, lng: {{ artist.long }} },
      mapTypeId: google.maps.MapTypeId.ROADMAP,
      mapTypeControl: false,
      zoomControl: true,
      zoomControlOptions: {
      position: google.maps.ControlPosition.LEFT_TOP,
    }
    });

    // Construct the circle for each value in citymap.
    // Note: We scale the area of the circle based on the population.

      // Add the circle for this city to the map.
      const cityCircle = new google.maps.Circle({
        strokeColor: "#fe3638",
        strokeOpacity: 0.8,
        strokeWeight: 2,
        fillColor: "#fe3638",
        fillOpacity: 0.35,
        map,
        center: { lat: {{ artist.lat }}, lng: {{ artist.long }} },
        radius: 20000,
      });

  }


    $(document).ready(function(){


    })

  </script>
  {% endblock %}

artApp/artApp/templates/index.html
{% extends 'layout.html' %}
{% load static %}
  {% block content %}

  <!-- Hero section-->
  <section class="bg-position-top-center bg-repeat-0 pt-5 pb-5 py-md-10 tns-carousel tns-controls-lg" style="background-image: url('{% static 'img/landingPhoto.jpg'%}');">
    <div class="container pt-4 mb-3 mb-lg-0">
      <div class="row">
        <div class="col-lg-5 col-md-6 col-sm-8 offset-lg-1">
          <h1 class="text-light mb-5">You can change <br>the life of the greatest <br> artists of Mexico</h1>
          <p class="fs-lg text-light pb-3 from-start delay-2">50% of the sales go to the masters. <br>To know more about our project click in the botton</p>
          <div class="d-flex align-items-center mb-5"><a class="btn btn-primary me-grid-gutter" href="{% url 'core:about' %}">Click here!</a></div>
        </div>
      </div>
    </div>
  </section>

    <div class="container-fluid">

      <div class="row">
        <div class="col-12 py-4 p-xl-5">

          <h3 class="mb-4">The greatest artesans of Mexico</h3>
          <hr class="my-4">


          <!-- Products grid-->
          <div class="row pt-3 mx-n2">
            {% for item in items %}

            <!-- Product-->
            <div class="col-lg-3 col-md-4 col-sm-6 col-6 px-2 mb-4" data-marker-id="{{ item.id }}">
              <div class="card product-card" >
                <a class="card-img-top d-block overflow-hidden" href="/artist?artist_id={{ item.artist.id }}&&item_id={{ item.id }}"><img class="center" src="{{ item.itemPhotoComplete.url }}" alt="Product"></a>
                <div class="card-body py-2"><a class="product-meta d-block fs-xs pb-1" href="/artist?artist_id={{ item.artist.id }}&&item_id={{ item.id }}">by {{ item.artist }}</a>

                  <a href="/artist?artist_id={{ item.artist.id }}&&item_id={{ item.id }}">
                  <h3 class="product-title fs-sm">{{ item.title }}</h3>
                  <div class="d-flex justify-content-between">
                    <div class="product-price"><span class="text-primary">{{ item.hours }} hours worked</span><br><span class="text-secondary">${{ item.price }}</span></div>

                  </div>
                  </a>
                  </div>
                </div>

              </div>

            {% endfor %}
          </div>

          <!-- Pagination -->
          <div class="pagination footers">
            <span class="step-links w-100 text-center">
            {% if items.has_previous %}
            <a href="?page=1">&laquo; Back</a>
            <a href="?page={{ items.previous_page_number }}">Back</a>
            {% endif %} <span class="current"> Page {{ items.number }} out of {{ items.paginator.num_pages }} </span>
            {% if items.has_next %} <a href="?page={{ items.next_page_number }}">Next</a>
            <a href="?page={{ items.paginator.num_pages }}">Last &raquo;</a> {% endif %}
            </span>
          </div>
        </div>
      </div>
    </div>


  {% endblock %}

artApp/artApp/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>ArtApp</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">

    <!-- ////////////////////////
        //// Start Directory ////
        ///////////////////////// -->

    <!-- Price Slider Stylesheets -->
    <link rel="stylesheet" href="{% static 'vendor/nouislider/nouislider.css' %}">
    <!-- Google fonts - Playfair Display-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&display=swap">
    <!-- swiper-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.4.1/css/swiper.min.css">
    <!-- Magnigic Popup-->
    <link rel="stylesheet" href="{% static 'vendor/magnific-popup/magnific-popup.css' %}">
    <!-- Leaflet Maps-->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css" integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ==" crossorigin="">
    <!-- theme stylesheet-->
    <!-- <link rel="stylesheet" href="{% static 'css/style.pink.css' %}" id="theme-stylesheet"> -->
    <!-- Google Maps stylesheet -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/maps.css' %}" />
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}">
    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
    <!-- Font Awesome CSS-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <!-- //////////////////////
        //// End Directory ////
        /////////////////////// -->

    <!-- //////////////////////
        //// Start Cartzilla ////
        /////////////////////// -->

    <!-- SEO Meta Tags-->
    <meta name="description" content="Cartzilla - Bootstrap E-commerce Template">
    <meta name="keywords" content="bootstrap, shop, e-commerce, market, modern, responsive,  business, mobile, bootstrap, html5, css3, js, gallery, slider, touch, creative, clean">
    <meta name="author" content="Createx Studio">
    <!-- Viewport-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Favicon and Touch Icons-->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'cartzilla/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'cartzilla/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'cartzilla/favicon-16x16.png' %}">
    <link rel="mask-icon" color="#fe6a6a" href="{% static 'cartzilla/safari-pinned-tab.svg' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="theme-color" content="#ffffff">
    <!-- Vendor Styles including: Font Icons, Plugins, etc.-->
    <link rel="stylesheet" media="screen" href="{% static 'cartzilla/vendor/simplebar/dist/simplebar.min.css' %}"/>
    <link rel="stylesheet" media="screen" href="{% static 'cartzilla/vendor/tiny-slider/dist/tiny-slider.css' %}"/>
    <link rel="stylesheet" media="screen" href="{% static 'cartzilla/vendor/drift-zoom/dist/drift-basic.min.css' %}"/>
    <!-- Main Theme Styles + Bootstrap-->
    <link rel="stylesheet" media="screen" href="{% static 'cartzilla/css/theme.css' %}">
    <!-- Main Theme Styles + Bootstrap-->
    <link rel="stylesheet" media="screen" href="{% static 'cartzilla/css/theme.min.css' %}">

    <!-- //////////////////////
        //// End Cartzilla ////
        /////////////////////// -->


  </head>
  <body style="padding-top: 72px;">
    <header class="header">
      <!-- Navbar-->
      <nav class="navbar navbar-expand-lg fixed-top shadow navbar-light bg-white">
        <div class="container-fluid">
          <div class="d-flex align-items-center"><a class="navbar-brand py-1" href="{% url 'core:index' %}"><img style="width: 40%;" src="{% static 'img/artezzanos.png' %}" alt="logo"></a>
          </div>
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
          <!-- Navbar Collapse -->
          <div class="collapse navbar-collapse " id="navbarCollapse">

            {% if categories %}
            <ul class="navbar-nav ">
            <li class="nav-item dropdown"><a class="nav-link  border-end" data-bs-toggle="dropdown"><i class="ci-view-grid me-2"></i>Categories</a>
              <ul class="dropdown-menu">
                {% for subcategory in subcategories %}
                <li class="dropdown">

                  <a class="dropdown-item "><img class="rounded-3 me-lg-2" width="30" height="30" src="{{ subcategory.category.categoryPhoto.url }}" alt="Photo">{{ subcategory.category }}</a>

                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="/categories?subcategory_id={{ subcategory.id }}">{{ subcategory }}</a></li>
                  </ul>
                </li>
                {% endfor %}
              </ul>
            </li>
            </ul>
            {% endif %}


            <ul class="navbar-nav ml-auto pe-lg-4 me-lg-3">
              <li class="nav-item"><a class="nav-link" href="{% url 'core:cart' %}">My Cart</a></li>
              {% if user.is_authenticated %}
              <li class="nav-item"><a class="nav-link" href="{% url 'core:logout' %}">Logout</a></li>
              <li class="nav-item nav-link">Hola, {{ user.email }}!</li>
              {% else %}
              <li class="nav-item"><a class="nav-link" href="{% url 'core:login' %}">Log in</a></li>
              <li class="nav-item"><a class="nav-link" href="{% url 'core:signup' %}">Sign up</a></li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
      <!-- /Navbar -->
    </header>


    {% block content %}
    {% endblock %}

    <!-- Toolbar for handheld devices (Default)-->
    <div class="handheld-toolbar">
      <div class="d-table table-layout-fixed w-100">
        <a class="d-table-cell handheld-toolbar-item" href="{% url 'core:index' %}">
        <span class="handheld-toolbar-icon"><i class="ci-menu"></i></span>
        <span class="handheld-toolbar-label">Menu</span>
        </a>

        <a class="d-table-cell handheld-toolbar-item" href="{% url 'core:cart' %}">
        <span class="handheld-toolbar-icon"><i class="ci-cart"></i>
        <span class="badge bg-primary rounded-pill ms-1" id="quantityModePhone">{{ car.quantity }}</span></span>
        <span class="handheld-toolbar-label" id="totalMoneyModePhone">$ {{ car.total }}</span>
        </a>
      </div>
    </div>

    <!-- Footer-->
    <footer class="position-relative z-index-10 d-print-none">
      <div class="pt-5 bg-secondary">
        <div class="container">
          <div class="row pb-2">
            <div class="col-md-6 text-center text-md-start mb-4">
              <div class="text-nowrap mb-4"><a class="fs-base text-dark mb-1" href="#">Artezzanos.com</a>
              </div>
              <div class="widget widget-links widget-dark">
                <ul class="widget-list d-flex flex-wrap justify-content-center justify-content-md-start">
                  <li class="widget-list-item me-4"><a class="widget-list-link" href="#">Outlets</a></li>
                  <li class="widget-list-item me-4"><a class="widget-list-link" href="#">Affiliates</a></li>
                  <li class="widget-list-item me-4"><a class="widget-list-link" href="#">Support</a></li>
                  <li class="widget-list-item me-4"><a class="widget-list-link" href="#">Privacy</a></li>
                  <li class="widget-list-item me-4"><a class="widget-list-link" href="#">Terms of use</a></li>
                </ul>
              </div>
            </div>
            <div class="col-md-6 text-center text-md-end mb-4">
              <div class="mb-3">
                <a class="btn-social bs-dark bs-twitter ms-2 mb-2" href="#"><i class="ci-twitter"></i></a>
                <a class="btn-social bs-dark bs-facebook ms-2 mb-2" href="#"><i class="ci-facebook"></i></a>
                <a class="btn-social bs-dark bs-instagram ms-2 mb-2" href="#"><i class="ci-instagram"></i></a>
                <a class="btn-social bs-dark bs-pinterest ms-2 mb-2" href="#"><i class="ci-pinterest"></i></a>
                <a class="btn-social bs-dark bs-youtube ms-2 mb-2" href="#"><i class="ci-youtube"></i></a>
              </div><img class="d-inline-block" src="{% static 'cartzilla/img/cards-alt.png' %}" width="187" alt="Payment methods">
            </div>
          </div>
          <div class="pb-4 fs-xs text-dark opacity-50 text-center text-md-start">© All rights reserved. Made with love.</div>
        </div>
      </div>
    </footer>

    <!-- ////////////////////// -->
    <!-- ///// Start Scripts // -->
    <!-- ////////////////////// -->

    <!-- jQuery-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap JS bundle - Bootstrap + PopperJS-->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- Magnific Popup - Lightbox for the gallery-->
    <script src="{% static 'vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>
    <!-- Smooth scroll-->
    <script src="{% static 'vendor/smooth-scroll/smooth-scroll.polyfills.min.js' %}"></script>
    <!-- Bootstrap Select-->
    <script src="{% static 'vendor/bootstrap-select/js/bootstrap-select.min.js' %}"></script>
    <!-- Object Fit Images - Fallback for browsers that don't support object-fit-->
    <script src="{% static 'vendor/object-fit-images/ofi.min.js' %}"></script>
    <!-- Swiper Carousel                       -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.4.1/js/swiper.min.js"></script>
    <script>var basePath = ''</script>
    <!-- Main Theme JS file -->
    <script src="{% static 'js/theme.js' %}"></script>



    <!-- Vendor scrits: js libraries and plugins-->
    <script src="{% static 'cartzilla/vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'cartzilla/vendor/simplebar/dist/simplebar.min.js' %}"></script>
    <script src="{% static 'cartzilla/vendor/tiny-slider/dist/min/tiny-slider.js' %}"></script>
    <script src="{% static 'cartzilla/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js' %}"></script>
    <script src="{% static 'cartzilla/vendor/drift-zoom/dist/Drift.min.js' %}"></script>
    <!-- Main theme script-->
    <script src="{% static 'cartzilla/js/theme.js' %}"></script>

    {% block js %}
    {% endblock %}

    <!-- ////////////////////// -->
    <!-- ///// End Scripts // -->
    <!-- ////////////////////// -->


  </body>
</html>

artApp/artApp/templates/login.html
{% extends 'layout.html' %}
{% load static %}
  {% block content %}

      <div class="modal-dialog" role="document" style = "margin-top: 136px;margin-bottom: 150px;">
        
        {% if errors %}
        <div class="alert alert-primary d-flex" role="alert">
          <div class="alert-icon">
            <i class="ci-bell"></i>
          </div>
          <div>{{errors}}</div>
        </div>
        {% endif %}

        <div class="modal-content">
          <div class="modal-body tab-content py-4">

            <form method="POST" class="tab-pane fade show active" id="signin" autocomplete="off">
              {% csrf_token %}
              {{ form.as_p }}
              <div class="mb-3 d-flex flex-wrap justify-content-between">
                <div >
                    <input class="btn btn-primary d-block btn-shadow" type="submit" name="login" value="login">
                </div>
                <a class="fs-sm" href="{% url 'core:password_reset' %}">Forgot password?</a>
              </div>

            </form>
          </div>
        </div>
      </div>


  {% endblock %}

artApp/artApp/templates/shop_cart.html
{% extends 'layout.html' %}
{% load static %}
  {% block content %}
  <!-- Body-->
  <body class="handheld-toolbar-enabled">


    <!-- Page Title-->
    <div class="page-title-overlap bg-light pt-4">
      <div class="container d-lg-flex justify-content-between py-2 py-lg-3">
        <div class="order-lg-1 pe-lg-4 text-center text-lg-start">
          <h1 class="h3 text-dark mb-0">Your cart</h1>
        </div>
      </div>
    </div>


    <div class="container pb-5 mb-2 mb-md-4" >
      <div class="row" style="margin-bottom: 157px;">
        <!-- List of items-->
        <section class="col-lg-8">
          <div class="d-flex justify-content-between align-items-center pt-3 pb-4 pb-sm-5 mt-1">
            <h2 class="h6 text-dark mb-0">Products</h2><a class="btn btn-outline-primary btn-sm ps-2" href="{% url 'core:index' %}"><i class="ci-arrow-left me-2"></i>Continue shopping</a>
          </div>
          {%for item in items%}
          <!-- Item-->
          <div class="d-sm-flex justify-content-between align-items-center my-2 pb-3 border-bottom">
            <div class="d-block d-sm-flex align-items-center text-center text-sm-start"><a class="d-inline-block flex-shrink-0 mx-auto me-sm-4" href="/artist?artist_id={{ item.item.artist.id }}&&item_id={{ item.item.id }}"><img src="{{ item.item.itemPhotoComplete.url }}" width="160" alt="Product"></a>
              <div class="pt-2">

                <h3 class="product-title fs-base"><a href="/artist?artist_id={{ item.item.artist.id }}&&item_id={{ item.item.id }}">{{ item.item.title }}</a></h3>
                <div class="fs-lg">$<span class="itemPrice">{{ item.item.price }}</span></div>
              </div>
            </div>
            <div class="pt-2 pt-sm-0 ps-sm-3 mx-auto mx-sm-0 text-center text-sm-start" style="max-width: 9rem;">
              <label class="form-label" for="quantity1">Quantity</label>
              <input type="hidden" class="id_item" value="{{item.item.id}}">
              <input class="form-control quantity" type="number" min="1" value="{{ item.quantityByItems }}">
              <button class="btn btn-link px-0 text-danger identifybotton remove" type="button"><i class="ci-close-circle me-2"></i><span class="fs-sm">Remove</span></button>
            </div>
          </div>
          {%endfor%}
        </section>
        <!-- Sidebar-->
        <aside class="col-lg-4 pt-4 pt-lg-0 ps-xl-5">
          <div class="bg-white rounded-3 shadow-lg p-4">
            <div class="py-2 px-xl-2">
              <div class="text-center mb-4 pb-3 border-bottom">
                <h2 class="h6 mb-3 pb-1">Subtotal</h2>
                <h3 class="fw-normal" id="totalMoney">$ {{ car.total }}</h3>
              </div>
              <a class="btn btn-primary btn-shadow d-block w-100 mt-4" href="{% url 'core:shipping' %}"><i class="ci-card fs-lg me-2"></i>Proceed to Checkout</a>
            </div>
          </div>
        </aside>
      </div>
    </div>


    <!-- Vendor scrits: js libraries and plugins-->
    <script src="{% static 'jquery/jquery.js' %}"></script>
    <script src="{% static 'cartzilla/vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'cartzilla/vendor/simplebar/dist/simplebar.min.js' %}"></script>
    <script src="{% static 'cartzilla/vendor/tiny-slider/dist/min/tiny-slider.js' %}"></script>
    <script src="{% static 'cartzilla/vendor/smooth-scroll/dist/smooth-scroll.polyfills.min.js' %}"></script>
    <!-- Main theme script-->
    <script src="{% static 'cartzilla/js/theme.min.js' %}"></script>

  </body>
  {% endblock %}

  {%block js%}
  <script src="{%static '/js/shop-cart.js'%}"></script>
  {%endblock%}